--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/UnknownOre/EnchantShopUI
branches:
- master
projects:
  EnchantShopUI:
    path: ""
    icon: "/logo.png"
    libs:
    - src: dktapps/pmforms/pmforms
      version: ^1.0.0
...
