name: EnchantUI
main: UnknownOre\EnchantUI\Main
version: 0.6
api: 3.0.0
load: POSTWORLD
author: UnknownOre, DragonfireHD98
permissions:
  eshop.command:
    default: true
    description: "use all EnchantUI Commands"
